% DRESS_BUILD  Compile the dress MEX file.
%
%   Run this script from the matlab/ directory (or adjust paths).
%   Requires: MATLAB with a configured C compiler (mex -setup).
%
%   Usage:
%     >> cd matlab
%     >> dress_build

fprintf('Compiling dress_mex ...\n');

mex('-O', ...
    ['-I' fullfile('..', 'libdress', 'include')], ...
    'CFLAGS=$CFLAGS -fopenmp', ...
    'LDFLAGS=$LDFLAGS -fopenmp', ...
    'dress_mex.c', ...
    fullfile('..', 'libdress', 'src', 'dress.c'), ...
    '-lm');

fprintf('Done. dress_mex.%s is ready.\n', mexext);

fprintf('Compiling delta_dress_mex ...\n');

mex('-O', ...
    ['-I' fullfile('..', 'libdress', 'include')], ...
    'CFLAGS=$CFLAGS -fopenmp', ...
    'LDFLAGS=$LDFLAGS -fopenmp', ...
    'delta_dress_mex.c', ...
    fullfile('..', 'libdress', 'src', 'dress.c'), ...
    fullfile('..', 'libdress', 'src', 'delta_dress.c'), ...
    '-lm');

fprintf('Done. delta_dress_mex.%s is ready.\n', mexext);

% Persistent DRESS MEX files
dress_src = fullfile('..', 'libdress', 'src', 'dress.c');
inc_flag  = ['-I' fullfile('..', 'libdress', 'include')];
omp_c     = 'CFLAGS=$CFLAGS -fopenmp';
omp_ld    = 'LDFLAGS=$LDFLAGS -fopenmp';

for name = {'dress_init_mex', 'dress_fit_obj_mex', 'dress_get_mex', ...
            'dress_result_mex', 'dress_free_mex'}
    fprintf('Compiling %s ...\n', name{1});
    mex('-O', inc_flag, omp_c, omp_ld, [name{1} '.c'], dress_src, '-lm');
    fprintf('Done. %s.%s is ready.\n', name{1}, mexext);
end
